name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2.0.0
        with:
          command: "earthly -V"
